import { MenuItem, Customer, StoreConfig, Voucher, OrderRecord, CustomerTestimonial } from '../types';

export const MONTHS_INDONESIA = [
  { value: 1, label: 'Januari' },
  { value: 2, label: 'Februari' },
  { value: 3, label: 'Maret' },
  { value: 4, label: 'April' },
  { value: 5, label: 'Mei' },
  { value: 6, label: 'Juni' },
  { value: 7, label: 'Juli' },
  { value: 8, label: 'Agustus' },
  { value: 9, label: 'September' },
  { value: 10, label: 'Oktober' },
  { value: 11, label: 'November' },
  { value: 12, label: 'Desember' },
];

export const BRAND = {
  name: 'Dulang Indonesia',
  shortName: 'Dulang',
  tagline: 'Dibuat dengan wajan panas & tulisan tangan',
  since: '2020',
  instagram: 'dulang_indonesia',
  whatsapp: '6287703397035',
  displayWhatsapp: '+62 877 0339 7035',
  location: 'Sidoarjo, Jawa Timur',
  locationDetail: 'Sidoarjo, Jawa Timur — dapur kecil deket Pasar Payan, yang sedia menyambut ceritamu',
  operatingHours: '10.00 - 19.30 (kalo habis ya tutup duluan)',
};

export const DEFAULT_STORE_CONFIG: StoreConfig = {
  heroImage: '/dulang-logo.png',
  heroHeadlineSub: 'digoreng jam 10 pagi\nhabis jam 8 malem',
  jamBukaTeks: '10.00 - 19.30 (kalo habis ya tutup duluan)',
  schedules: [
    {
      jam: '03.00',
      teks: 'bangun, ngadon kulit risoles. masih ngantuk tapi wajan udah panas.',
      rot: '-1.2deg',
    },
    {
      jam: '10.00',
      teks: 'goreng pertama. yang antri di WA udah belasan orang. mayo masih lumer.',
      rot: '1.2deg',
    },
    {
      jam: '15.00',
      teks: 'istirahat bentar, lap wajan. cerita-cerita santai sama tetangga komplek.',
      rot: '-0.8deg',
    },
    {
      jam: '19.30',
      teks: 'tutup. kalo masih ada sisa, bagi-bagi ke musala. besok goreng lagi yaa.',
      rot: '1deg',
    },
  ],
  ownerPin: 'dulang2020',
  isStoreClosed: false,
  closedReason: 'Maaf lagi nggak goreng dulu, hari ini masak di dapur sendiri ya. -Tim Dulang Indonesia',
  activeKloter: 'Kloter Siang (13.00) • Sedang Digoreng Panas 🔥',
  isTomorrowOrderOpen: true,
  tomorrowOrderNote: 'Amankan kuota risoles besok! Digulung & digoreng fresh besok subuh khusus pesananmu.',
  enableDeliveryOption: false, // Default mati/pasif (kebanyakan ambil di tempat, aktifkan bila perlu)
  pickupAddressNote: 'Ambil di Dapur Dulang (Jl. Diponegoro No. 12, Pagerwojo - Dekat Pasar)',
  deliveryRates: {
    'Sidoarjo Kota': 6000,
    'Buduran': 7000,
    'Candi': 8000,
    'Sukodono': 9000,
    'Gedangan': 10000,
    'Waru': 13000,
    'Sedati': 12000,
    'Taman': 14000,
    'Wonoayu': 11000,
    'Tulangan': 12000,
    'Tanggulangin': 10000,
    'Porong': 13000,
    'Krembung': 15000,
    'Krian': 16000,
    'Prambon': 17000,
    'Balongbendo': 19000,
    'Tarik': 20000,
    'Jabon': 18000,
  },
  bankBCA: '8290-888-291 a/n Tim Dulang Indonesia',
  bankMandiri: '141-00-1928374-1 a/n Tim Dulang Indonesia',
  bankBRI: '0089-01-082910-50-3 a/n Tim Dulang Indonesia',
  qrisTeks: 'Mendukung QRIS BCA, Mandiri, BRI, GoPay, OVO, ShopeePay, Dana, dll',
};

export const DEFAULT_SIDOARJO_DELIVERY_RATES: Record<string, number> = {
  'Sidoarjo Kota': 6000,
  'Buduran': 7000,
  'Candi': 8000,
  'Sukodono': 9000,
  'Gedangan': 10000,
  'Waru': 13000,
  'Sedati': 12000,
  'Taman': 14000,
  'Wonoayu': 11000,
  'Tulangan': 12000,
  'Tanggulangin': 10000,
  'Porong': 13000,
  'Krembung': 15000,
  'Krian': 16000,
  'Prambon': 17000,
  'Balongbendo': 19000,
  'Tarik': 20000,
  'Jabon': 18000,
};


// Delivery Regions: Sidoarjo, Surabaya, Gresik & Luar Kota
export interface DeliveryRegionGroup {
  group: string;
  areas: string[];
}

export const DELIVERY_REGIONS: DeliveryRegionGroup[] = [
  {
    group: 'Sidoarjo (Dapur Utama)',
    areas: [
      'Sidoarjo Kota',
      'Waru',
      'Gedangan',
      'Buduran',
      'Candi',
      'Sukodono',
      'Taman',
      'Sedati',
      'Krian',
      'Tulangan',
      'Wonoayu',
      'Porong',
      'Tanggulangin',
      'Krembung',
      'Balongbendo',
      'Prambon',
      'Tarik',
      'Jabon',
    ],
  },
  {
    group: 'Surabaya',
    areas: [
      'Surabaya Selatan (Rungkut, Wonokromo, Gayungan, Jambangan, Tenggilis)',
      'Surabaya Timur (Sukolilo, Gubeng, Mulyorejo, Gunung Anyar)',
      'Surabaya Barat (Wiyung, Sambikerep, Karangpilang, Dukuh Pakis, Tandes)',
      'Surabaya Pusat (Tegalsari, Genteng, Bubutan, Simokerto)',
      'Surabaya Utara (Kenjeran, Semampir, Pabean Cantian, Krembangan)',
    ],
  },
  {
    group: 'Gresik & Sekitarnya',
    areas: [
      'Gresik Kota',
      'Menganti',
      'Driyorejo',
      'Kebomas',
    ],
  },
  {
    group: 'Luar Kota / Ekspedisi',
    areas: [
      'Luar Kota (Frozen Paxel / 1 Hari Sampai)',
      'Lainnya (Tulis detail kota di alamat)',
    ],
  },
];

export const INDONESIA_CITIES: string[] = [
  'Kabupaten Sidoarjo',
  'Kota Surabaya',
  'Kabupaten Gresik',
  'Kabupaten Pasuruan',
  'Kabupaten Mojokerto',
  'Luar Kota Lainnya',
];

export const CITY_DISTRICTS: Record<string, string[]> = {
  'Kabupaten Sidoarjo': [
    'Sidoarjo Kota',
    'Buduran',
    'Candi',
    'Gedangan',
    'Waru',
    'Sedati',
    'Sukodono',
    'Taman',
    'Krian',
    'Tulangan',
    'Wonoayu',
    'Tanggulangin',
    'Porong',
    'Krembung',
    'Balongbendo',
    'Prambon',
    'Tarik',
    'Jabon',
  ],
  'Kota Surabaya': [
    'Rungkut',
    'Wonokromo',
    'Gubeng',
    'Sukolilo',
    'Tegalsari',
    'Genteng',
    'Wiyung',
    'Dukuh Pakis',
    'Gayungan',
    'Jambangan',
    'Tenggilis Mejoyo',
    'Gunung Anyar',
    'Mulyorejo',
    'Sawahan',
    'Wonocolo',
    'Karangpilang',
    'Sambikerep',
    'Tandes',
    'Kenjeran',
    'Tambaksari',
    'Semampir',
    'Pabean Cantian',
    'Krembangan',
    'Bubutan',
    'Simokerto',
    'Benowo',
    'Pakal',
    'Asemrowo',
    'Bulak',
    'Lakarsantri',
    'Sukomanunggal',
  ],
  'Kabupaten Gresik': [
    'Driyorejo',
    'Menganti',
    'Kebomas',
    'Gresik Kota',
    'Manyar',
    'Cerme',
    'Kedamean',
    'Wringinanom',
  ],
  'Kabupaten Pasuruan': [
    'Bangil',
    'Beji',
    'Gempol',
    'Pandaan',
    'Prigen',
    'Sukorejo',
    'Purwosari',
  ],
  'Kabupaten Mojokerto': [
    'Mojosari',
    'Puri',
    'Ngoro',
    'Pungging',
    'Trowulan',
    'Bangsal',
  ],
  'Luar Kota Lainnya': [
    'Luar Kota (Ekspedisi Paxel Frozen)',
    'Lainnya (Luar Jawa Timur)',
  ],
};

export const ALL_DELIVERY_AREAS: string[] = DELIVERY_REGIONS.flatMap((r) => r.areas);
export const SIDOARJO_AREAS = CITY_DISTRICTS['Kabupaten Sidoarjo'];


// Default Menus Riil Dapur Dulang Indonesia (8 Menu Utama)
export const DEFAULT_MENUS: MenuItem[] = [
  {
    id: 'menu-1',
    nama: 'Risol Mayo',
    harga: 3500,
    deskripsi: 'Kulit lembut buatan subuh, smoked beef gurih, telur rebus, dan mayo lumer melimpah.',
    tersedia: true,
    opsi: ['Saos Pedas', 'Saos Tidak Pedas', 'cabai aja'],
  },
  {
    id: 'menu-2',
    nama: 'Risol Rogut',
    harga: 3500,
    deskripsi: 'Rogut ayam wortel creamy gurih berempah khas resep wajan panas sejak 2020.',
    tersedia: true,
    opsi: ['Saos Pedas', 'Saos Tidak Pedas', 'cabai aja'],
  },
  {
    id: 'menu-3',
    nama: 'Lumpia Sayur',
    harga: 2500,
    deskripsi: 'Lumpia renyah isi tumisan rebung dan sayuran segar gurih mantap.',
    tersedia: true,
    opsi: ['komplit', 'daun bawang aja', 'cabai aja'],
  },
  {
    id: 'menu-4',
    nama: 'Pisang Coklat',
    harga: 2500,
    deskripsi: 'Pisang manis legit berbalut cokelat premium yang meletus di mulut. Luar renyah, dalam melted.',
    tersedia: true,
  },
  {
    id: 'menu-5',
    nama: 'Tahu Isi Pedas',
    harga: 3000,
    deskripsi: 'Tahu goreng renyah isi sayur pedas gurih nagih, pas buat cemilan anget.',
    tersedia: true,
    opsi: ['Pedas', 'Tidak Pedas', 'cabai aja'],
  },
  {
    id: 'menu-6',
    nama: 'Ote-Ote',
    harga: 2000,
    deskripsi: 'Bakwan sayur / ote-ote khas Jawa Timur yang renyah di luar, lembut dan gurih di dalam.',
    tersedia: true,
  },
  {
    id: 'menu-7',
    nama: 'Kebab',
    harga: 10000,
    deskripsi: 'Tortilla panggang isi irisan daging lezat, sayuran segar, dan racikan saus spesial.',
    tersedia: true,
    opsi: ['Pedas', 'Sedang', 'Tidak Pedas'],
  },
  {
    id: 'menu-8',
    nama: 'Burger',
    harga: 13000,
    deskripsi: 'Roti bun lembut dengan patty daging gurih, sayuran segar, dan siraman saus mantap.',
    tersedia: true,
    opsi: ['Pedas', 'Sedang', 'Tidak Pedas'],
  },
  {
    id: 'menu-9',
    nama: 'Risol Mayo Frozen (Isi 5)',
    harga: 17000,
    deskripsi: 'Pack hemat isi 5 pcs risoles mayo siap goreng di rumah, tahan simpan kulkas/freezer.',
    tersedia: true,
    variantType: 'frozen',
  },
  {
    id: 'menu-10',
    nama: 'Risol Rogut Frozen (Isi 5)',
    harga: 17000,
    deskripsi: 'Pack hemat isi 5 pcs risoles rogut ayam sayur creamy siap goreng kapan saja.',
    tersedia: true,
    variantType: 'frozen',
  },
  {
    id: 'menu-11',
    nama: 'Kebab Frozen',
    harga: 25000,
    deskripsi: 'Pack isi kebab tortilla daging siap panggang teflon hangat di rumah.',
    tersedia: true,
    variantType: 'frozen',
  },
  {
    id: 'menu-12',
    nama: 'Risol Mayo Frozen (Isi 10)',
    harga: 33000,
    deskripsi: 'Kemasan box isi 10 pcs risoles mayo beku super mantap buat stok keluarga.',
    tersedia: true,
    variantType: 'frozen',
  },
  {
    id: 'menu-13',
    nama: 'Risol Rogut Frozen (Isi 10)',
    harga: 33000,
    deskripsi: 'Kemasan box isi 10 pcs risoles rogut beku gurih berempah.',
    tersedia: true,
    variantType: 'frozen',
  },
];

// Seed initial loyal customers for testing & simulation
export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    qr_code_id: 'DULANG-042',
    name: 'Rina',
    wa: '6287703397035',
    address: 'Perumahan Kahuripan Nirwana Blok C-12',
    area: 'Sidoarjo Kota',
    favorite_menu: 'Risol Mayo',
    favorite_option: 'Saos Pedas',
    total_orders: 5,
    total_spent: 85000,
    status: 'Sultan Dulang',
    consent_at: '2026-08-10T10:00:00Z',
    first_scan_at: '2026-08-10T10:00:00Z',
    last_scan_at: '2026-09-20T14:30:00Z',
    birth_day: 27,
    birth_month: 9, // September (Hari ini ulang tahun!)
    notes: 'Suka mayo lumer pedas, selalu pesan min 5 box',
  },
  {
    id: 'cust-2',
    qr_code_id: 'DULANG-015',
    name: 'Budi Santoso',
    wa: '6281234567890',
    address: 'Jl. Raya Tropodo No. 45',
    area: 'Waru',
    favorite_menu: 'Risol Rogut',
    favorite_option: 'cabai aja',
    total_orders: 3,
    total_spent: 65000,
    status: 'Setia',
    consent_at: '2026-08-15T11:20:00Z',
    first_scan_at: '2026-08-15T11:20:00Z',
    last_scan_at: '2026-09-18T16:15:00Z',
    birth_day: 14,
    birth_month: 8, // Agustus
    notes: 'Langganan rogut ayam sarapan pagi, suka cabe ceplusan',
  },
  {
    id: 'cust-3',
    qr_code_id: 'DULANG-088',
    name: 'Anisa Rahma',
    wa: '6285678901234',
    address: 'Pondok Jati Blok AK-04',
    area: 'Buduran',
    favorite_menu: 'Pisang Coklat',
    favorite_option: 'Sedang',
    total_orders: 1,
    total_spent: 33000,
    status: 'Baru',
    consent_at: '2026-09-22T09:15:00Z',
    first_scan_at: '2026-09-22T09:15:00Z',
    last_scan_at: '2026-09-22T09:15:00Z',
    birth_day: 5,
    birth_month: 11, // November
    notes: 'Camilan manis sore, suka piscok lumer',
  },
];

// Seed initial personalized vouchers (Voucher Beranak & Tiket Rahasia)
export const DEFAULT_VOUCHERS: Voucher[] = [
  {
    code: 'AMANDA-LUMER-24',
    recipientName: 'Amanda',
    discountType: 'nominal',
    discountValue: 10000,
    minOrder: 40000,
    description: 'Traktiran Spesial buat Sobat Dulang',
    isUsed: false,
    createdAt: '2026-09-20T00:00:00Z',
    childVoucher: {
      title: 'Tiket Emas Dapur: Bonus 2 Risoles Rogout Hangat',
      perk: 'Gratis 2 Risoles Rogout Hangat',
      condition: 'Otomatis aktif untuk pesanan berikutnya min. 3 box dalam 7 hari',
      unlockCode: 'AMANDA-BONUS-ROGOUT',
    },
  },
  {
    code: 'DULANG-SERU-88',
    recipientName: 'Teman Dulang',
    discountType: 'percent',
    discountValue: 15,
    minOrder: 35000,
    description: 'Voucher Hangat Perkenalan Dapur',
    isUsed: false,
    createdAt: '2026-09-22T00:00:00Z',
    childVoucher: {
      title: 'Tiket Rahasia: Ekstra 1 Cup Mayo Pedas Gurih',
      perk: 'Gratis Ekstra Saus Mayo Pedas',
      condition: 'Berlaku saat repeat order kapan saja',
      unlockCode: 'DULANG-EXTRA-MAYO',
    },
  },
  {
    code: 'TETANGGA-GURIH-10',
    recipientName: 'Tetangga Komplek',
    discountType: 'nominal',
    discountValue: 5000,
    minOrder: 0,
    description: 'Potongan Hangat Tetangga Tanpa Minimal Beli',
    isUsed: false,
    createdAt: '2026-09-25T00:00:00Z',
  },
];

// Locked Copywriting Texts - PRD Anti-Halu v2.0 Source of Truth
export const LOCKED_COPY = {
  heroH1: 'Sudah makan? Jangan biarkan tubuhmu kelaparan',
  heroSub: 'bukan restoran, bukan cafe, bukan cloud kitchen. cuma dapur kecil di Sidoarjo yang bangun jam 3 pagi buat goreng risoles anget.',
  psWajib: 'tunggu agak dingin dulu, biar kamu nyaman makannya',
  pillBest: 'baru goreng • masih anget',
  pillScan: 'scan dulu • masih anget',
  pillHot: 'baru goreng • masih anget',
  qrNoteLeft: 'QR-nya di sini → kecil biar gak norak',
  qrScanNote: 'kangen? scan ini yaa ↳',
  qrDoodles: '✨ 💛 lumer~',
  waMain: 'Dulang, aku kangen yang anget-anget',
  waCheckout: 'Dulang, aku kangen yang anget-anget',
  toastSuccess: 'yey, masuk dapur!',
  toastReorder: 'yeeee kapan-kapan pesen lagi',
  toastPinError: 'kode salah, coba lagi',
  footer: '© 2020 Dulang Indonesia — dibuat dengan wajan panas & tulisan tangan',
  badgeSince: 'sejak 2020',
};

// --- DEFAULT TESTIMONIALS PELANGGAN (KARTU MEMO KULKAS) ---
export const DEFAULT_TESTIMONIALS: CustomerTestimonial[] = [
  {
    id: 'testi-1',
    customer_name: 'Kak Rina',
    area: 'Sidoarjo Kota',
    comment: 'Mayonya beneran lumer pas gigitan pertama! Paling suka opsi Saos Pedasnya, nagih banget buat camilan sore.',
    favorite_menu: 'Risol Mayo',
    created_at: '2026-09-24T14:00:00Z',
    is_active: true,
    rating: 5,
  },
  {
    id: 'testi-2',
    customer_name: 'Mas Budi',
    area: 'Waru',
    comment: 'Risol Rogutnya juara. Ayam wortelnya padet dan berempah, bukan sekadar tepung. Langganan tiap ada arisan.',
    favorite_menu: 'Risol Rogut',
    created_at: '2026-09-22T10:30:00Z',
    is_active: true,
    rating: 5,
  },
  {
    id: 'testi-3',
    customer_name: 'Bunda Dwi',
    area: 'Gedangan',
    comment: 'Anak-anak biasanya susah makan sayur, tapi lumpia sayurnya Dulang ludes! Renyahnya tahan lama walau dibawa pulang.',
    favorite_menu: 'Lumpia Sayur',
    created_at: '2026-09-20T16:15:00Z',
    is_active: true,
    rating: 5,
  },
  {
    id: 'testi-4',
    customer_name: 'Kak Amanda',
    area: 'Buduran',
    comment: 'Kebab sama burgernya tebel dan dagingnya berasa banget. Tim Dulang pelayanannya ramah pol!',
    favorite_menu: 'Kebab',
    created_at: '2026-09-18T19:00:00Z',
    is_active: true,
    rating: 5,
  },
];

// --- SEED CONTOH DATA TRANSAKSI PENJUALAN AWAL ---
export const DEFAULT_ORDERS: OrderRecord[] = [
  {
    id: 'ORD-101',
    customer_name: 'Rina',
    customer_wa: '6287703397035',
    customer_qr_id: 'DULANG-042',
    items: [
      { menu_id: 'menu-1', nama: 'Risol Mayo', harga: 3500, qty: 6, pilihanOpsi: 'Saos Pedas' },
      { menu_id: 'menu-4', nama: 'Pisang Coklat', harga: 2500, qty: 4 },
    ],
    total_price: 31000,
    payment_method: 'qris',
    status: 'lunas',
    created_at: '2026-09-27T08:30:00Z',
    completed_at: '2026-09-27T08:45:00Z',
    channel: 'web_wa',
    notes: 'Banyakin cabe rawitnya yaa',
  },
  {
    id: 'ORD-102',
    customer_name: 'Budi Santoso',
    customer_wa: '6281234567890',
    customer_qr_id: 'DULANG-015',
    items: [
      { menu_id: 'menu-2', nama: 'Risol Rogut', harga: 3500, qty: 10, pilihanOpsi: 'Saos Tidak Pedas' },
    ],
    total_price: 35000,
    payment_method: 'transfer',
    status: 'lunas',
    created_at: '2026-09-27T09:15:00Z',
    completed_at: '2026-09-27T09:30:00Z',
    channel: 'web_wa',
  },
  {
    id: 'ORD-103',
    customer_name: 'Pak RT',
    items: [
      { menu_id: 'menu-6', nama: 'Ote-Ote', harga: 2000, qty: 5 },
      { menu_id: 'menu-5', nama: 'Tahu Isi Pedas', harga: 3000, qty: 5, pilihanOpsi: 'Pedas' },
    ],
    total_price: 25000,
    payment_method: 'tunai',
    status: 'lunas',
    created_at: '2026-09-27T10:00:00Z',
    completed_at: '2026-09-27T10:10:00Z',
    channel: 'walk_in',
    notes: 'Beli langsung di dapur',
  },
  {
    id: 'ORD-104',
    customer_name: 'Anisa Rahma',
    customer_wa: '6285678901234',
    customer_qr_id: 'DULANG-088',
    items: [
      { menu_id: 'menu-7', nama: 'Kebab', harga: 10000, qty: 2, pilihanOpsi: 'Sedang' },
      { menu_id: 'menu-8', nama: 'Burger', harga: 13000, qty: 1, pilihanOpsi: 'Pedas' },
    ],
    total_price: 33000,
    status: 'menunggu',
    created_at: '2026-09-27T11:00:00Z',
    channel: 'web_wa',
    notes: 'Kirim kloter siang',
  },
];
